preprocess:
  old_dataset_path: "/home/olx/datasets/ShapeNetCore.v2.PC15k" # ---- TO SPECIFY ----
  new_dataset_path: "/home/olx/datasets/shapenet_torch" # ---- TO SPECIFY ----
  num_pts: 2048

train:
  enable_checkpointing: true
  categ: chair # airplane, table, etc. # ---- TO SPECIFY ----
  dataset_path: /home/olx/datasets/shapenet_torch # ---- TO SPECIFY ----
  categ_to_id_path: categ_to_id.json
  float32_matmul_precision: medium
  precision: 16-mixed
  num_workers: auto
  max_epochs: 100
  lr: 0.001
  batch_size: 32
  accumulate_grad_batches: 4
  gradient_clip_val: 1.0
  check_val_every_n_epoch: 1
  log_every_n_steps: 10

sample:
    ckpt_path: /home/olx/FlowMatching-PointClouds/chair-epoch43.ckpt # ---- TO SPECIFY ----
    num_steps: 100
    num_pts: 2048